name: Setup Ruby
description: Sets up Ruby and installs dependencies (caller must check out code first)

runs:
  using: "composite"
  steps:
    - name: Install libvips
      shell: bash
      run: |
        sudo apt-get update        
        sudo apt-get install --no-install-recommends libvips
    - uses: ruby/setup-ruby@v1
      env:
        BUNDLE_JOBS: 4
        BUNDLE_RETRY: 3
      with:
        ruby-version: .ruby-version
        bundler-cache: true

