name: Setup Ruby
description: Checks out code, sets up Ruby, and installs dependencies

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Install libvips
      shell: bash
      run: |
        sudo apt-get update        
        sudo apt-get install --no-install-recommends libvips
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true
        bundler-install-args: --jobs 4 --retry 3

