name: Ruby CI
permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      dockerImageTag:
        description: 'Docker image tag'
        required: false
        type: string
  
  push:
    branches: [ main, master ]
    tags:
      - 'v**'
  pull_request:
    branches: [ main, master ]

env:
  SHOW_CONTAINER_LOGS: true
  DISABLE_CHROME_SANDBOX: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Ruby Environment
        uses: ./.github/actions/setup-ruby
      - name: Lint with RuboCop
        run: |
          bundle install --jobs 4 --retry 3
          bundle exec rubocop

  gem-build:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Ruby Environment
        uses: ./.github/actions/setup-ruby
      - name: Build gem
        run: |
          bundle exec rake build
      - name: Upload gem
        uses: actions/upload-artifact@v7
        with:
          name: bidi2pdf-gem
          path: pkg/

  unit-test:
    needs: lint
    uses: ./.github/workflows/run-rspec-tests.yml
    with:
      test_tag: unit
      coverage_artifact_name: unit-coverage
      log_artifact_name: unit-log

  integration-test:
    needs: lint
    uses: ./.github/workflows/run-rspec-tests.yml
    with:
      test_tag: integration
      coverage_artifact_name: integration-coverage
      log_artifact_name: integration-log

  acceptance-test:
    needs: lint
    uses: ./.github/workflows/run-rspec-tests.yml
    with:
      test_tag: acceptance
      coverage_artifact_name: acceptance-coverage
      log_artifact_name: acceptance-log
      upload_pdf: true

